version: '3'

services:
  postgres:
    image: postgres:latest
    container_name: t_sql
    volumes:
      - ./scripts:/scripts
      - ./scripts/0-create-database.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"